application: everydaykenneth-142007
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|jpeg|ttf|woff|eot|svg|woff2))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|jpeg|tff|woff|eot|svg|woff2))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: main.py
